{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "frontend.fullname" . }}-pvc
  labels:
    app.kubernetes.io/name: {{ include "frontend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes: {{ toYaml .Values.persistence.accessModes | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
{{- end }}