replicaCount: 1

image:
  repository: ajaykumarchoda8143/frontend
  tag: v10
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

persistence:
  enabled: true
  storageClassName: azurefile-csi
  size: 5Gi
  accessModes:
    - ReadWriteMany    
  mountPath: /data
  existingClaim: ""              